import { Seva, SevaCategory } from './types';

export const sevaCategories: { id: SevaCategory; label: string }[] = [
    { id: 'daily', label: 'Daily Sevas' },
    { id: 'weekly', label: 'Weekly Sevas' },
    { id: 'monthly', label: 'Monthly Sevas' },
    { id: 'festival', label: 'Festival Sevas' },
    { id: 'special', label: 'Special Sevas' },
];

export const sevas: Seva[] = [
    {
        id: '1',
        slug: 'abhishekam',
        name: 'Abhishekam',
        shortDescription: 'Sacred ritual bathing of Lord Ganesha with milk, honey, and sacred waters',
        fullDescription: 'Abhishekam is one of the most sacred rituals performed for Lord Ganesha. The deity is bathed with panchamrit (five sacred substances), holy waters, and adorned with flowers while chanting powerful mantras. This seva brings immense purification and divine blessings.',
        benefits: [
            'Removes obstacles from life',
            'Purification of mind and soul',
            'Grants success in new ventures',
            'Brings prosperity and peace',
        ],
        requirements: [
            'Devotees should arrive 15 minutes early',
            'Traditional attire recommended',
            'Fasting optional but encouraged',
        ],
        duration: '45 minutes',
        timing: ['morning', 'evening'],
        suggestedDonation: {
            min: 501,
            recommended: 1001,
        },
        category: 'daily',
        frequency: 'daily',
        tags: ['Popular', 'Purification'],
        featured: true,
    },
    {
        id: '2',
        slug: 'archana',
        name: 'Archana',
        shortDescription: 'Offer 108 names of Lord Ganesha with flowers and sacred chants',
        fullDescription: 'Archana is the offering of flowers and bilva leaves while chanting the 108 sacred names of Lord Ganesha. Each name represents a divine quality and brings specific blessings to the devotee.',
        benefits: [
            'Fulfillment of wishes',
            'Mental clarity and focus',
            'Protection from negative energies',
            'Family harmony',
        ],
        requirements: [
            'Carry your sankalpa (intention)',
            'Names of family members for blessings',
        ],
        duration: '20 minutes',
        timing: ['morning', 'evening'],
        suggestedDonation: {
            min: 51,
            recommended: 101,
        },
        category: 'daily',
        frequency: 'daily',
        tags: ['Quick', 'Family'],
        featured: false,
    },
    {
        id: '3',
        slug: 'sahasranamarchana',
        name: 'Sahasranama Archana',
        shortDescription: 'Chanting of 1000 names of Lord Ganesha with elaborate offerings',
        fullDescription: 'An extended and powerful seva where 1000 sacred names of Lord Ganesha are chanted with offerings of flowers, modaks, and sacred items. This is one of the most auspicious sevas for major life events.',
        benefits: [
            'Removes major obstacles',
            'Success in important endeavors',
            'Divine protection',
            'Spiritual elevation',
        ],
        requirements: [
            'Prior booking required (2 days advance)',
            'Devotees may participate in chanting',
            'Traditional dress mandatory',
        ],
        duration: '2 hours',
        timing: ['morning'],
        suggestedDonation: {
            min: 2001,
            recommended: 5001,
        },
        category: 'special',
        frequency: 'on-request',
        tags: ['Premium', 'Major Events'],
        featured: true,
    },
    {
        id: '4',
        slug: 'modaka-offering',
        name: 'Modaka Naivedyam',
        shortDescription: "Offering of Lord Ganesha's favorite sweet with special prayers",
        fullDescription: 'Modaka, the favorite prasadam of Lord Ganesha, is prepared with devotion and offered with special prayers. The blessed prasadam is distributed to all devotees.',
        benefits: [
            'Sweetness in relationships',
            'Joy and happiness',
            'Divine grace',
            'Removal of bitterness',
        ],
        requirements: [
            'Modakas prepared in temple kitchen',
            'Prasadam distribution after puja',
        ],
        duration: '30 minutes',
        timing: ['morning', 'evening'],
        suggestedDonation: {
            min: 251,
            recommended: 501,
        },
        category: 'daily',
        frequency: 'daily',
        tags: ['Popular', 'Prasadam'],
        featured: false,
    },
    {
        id: '5',
        slug: 'rudrabhishekam',
        name: 'Rudrabhishekam',
        shortDescription: 'Powerful abhishekam with Rudram chanting for Lord Ganesha',
        fullDescription: 'A powerful combination of abhishekam performed while chanting the sacred Rudram. This seva invokes the blessings of both Lord Shiva and Lord Ganesha for comprehensive divine grace.',
        benefits: [
            'Removes severe obstacles',
            'Health and healing',
            'Protection from adversities',
            'Spiritual strength',
        ],
        requirements: [
            'Advance booking recommended',
            'Devotees may participate in chanting',
            'Fasting till completion recommended',
        ],
        duration: '1.5 hours',
        timing: ['morning'],
        suggestedDonation: {
            min: 1501,
            recommended: 3001,
        },
        category: 'weekly',
        frequency: 'weekly',
        tags: ['Powerful', 'Healing'],
        featured: false,
    },
    {
        id: '6',
        slug: 'alankara-seva',
        name: 'Alankara Seva',
        shortDescription: 'Decorating the deity with flowers, ornaments, and sacred adornments',
        fullDescription: 'Participate in the sacred decoration of Lord Ganesha with fresh flowers, traditional ornaments, and beautiful silks. This seva allows devotees to serve the Lord directly.',
        benefits: [
            'Beauty and grace in life',
            'Artistic enhancement',
            'Divine connection',
            'Merit (punya)',
        ],
        requirements: [
            'Prior registration required',
            'Guidance from temple priests',
            'Clean hands and pure heart',
        ],
        duration: '40 minutes',
        timing: ['morning'],
        suggestedDonation: {
            min: 751,
            recommended: 1501,
        },
        category: 'weekly',
        frequency: 'weekly',
        tags: ['Interactive', 'Decorative'],
        featured: false,
    },
    {
        id: '7',
        slug: 'ganapati-homam',
        name: 'Ganapati Homam',
        shortDescription: 'Sacred fire ritual invoking Lord Ganesha with powerful mantras',
        fullDescription: 'A traditional fire ceremony performed with specific herbs, ghee, and sacred materials while chanting Ganapati mantras. The sacred fire acts as a divine messenger carrying prayers to Lord Ganesha.',
        benefits: [
            'Removal of all obstacles',
            'Success in new beginnings',
            'Business prosperity',
            'Karmic purification',
        ],
        requirements: [
            'Booking 3 days in advance',
            'Family members can participate',
            'Bring new clothes for after ceremony',
        ],
        duration: '2.5 hours',
        timing: ['morning'],
        suggestedDonation: {
            min: 3001,
            recommended: 5001,
        },
        category: 'monthly',
        frequency: 'monthly',
        tags: ['Premium', 'Fire Ritual'],
        featured: true,
    },
    {
        id: '8',
        slug: 'vinayaka-chaturthi-special',
        name: 'Vinayaka Chaturthi Special Puja',
        shortDescription: 'Grand celebration on the monthly Chaturthi with elaborate rituals',
        fullDescription: 'Special elaborate puja performed on Chaturthi (4th day) of every month, which is sacred to Lord Ganesha. Includes abhishekam, archana, homam, and prasadam distribution.',
        benefits: [
            'Complete obstacle removal',
            'Fulfillment of desires',
            'Divine blessings for entire month',
            'Spiritual upliftment',
        ],
        requirements: [
            'Registration by previous Chaturthi',
            'Participation throughout ceremony',
            'Fasting recommended',
        ],
        duration: '3 hours',
        timing: ['morning'],
        suggestedDonation: {
            min: 2001,
            recommended: 5001,
        },
        category: 'monthly',
        frequency: 'monthly',
        tags: ['Festival', 'Chaturthi'],
        featured: false,
    },
    {
        id: '9',
        slug: 'ganesh-chaturthi-seva',
        name: 'Ganesh Chaturthi Maha Seva',
        shortDescription: 'Grand annual celebration of Lord Ganesha\'s birthday with 10-day festivities',
        fullDescription: 'The most auspicious festival celebrating the birth of Lord Ganesha. Ten days of continuous celebrations including daily abhishekams, cultural programs, and culminating in Anantha Chaturdashi.',
        benefits: [
            'Year-long blessings',
            'Major obstacle removal',
            'Community harmony',
            'Spiritual merit for generations',
        ],
        requirements: [
            'Advance registration (1 month prior)',
            'Daily participation optional',
            'Special passes for Visarjana ceremony',
        ],
        duration: '10 days',
        timing: ['full-day'],
        suggestedDonation: {
            min: 5001,
            recommended: 11000,
        },
        category: 'festival',
        frequency: 'yearly',
        tags: ['Grand Festival', 'Annual'],
        featured: false,
    },
    {
        id: '10',
        slug: 'anna-dana',
        name: 'Anna Dana (Food Offering)',
        shortDescription: 'Sponsor meals for devotees and serve the community',
        fullDescription: 'The sacred act of feeding devotees through temple prasadam. Sponsor breakfast, lunch, or dinner for all temple visitors, fulfilling the divine service of anna dana.',
        benefits: [
            'Supreme merit (Anna dana maha daanam)',
            'Prosperity and abundance',
            'Removal of hunger-related karma',
            'Community service',
        ],
        requirements: [
            'Book 1 week in advance',
            'Menu coordinated with temple',
            'Can participate in serving',
        ],
        duration: 'Meal time',
        timing: ['morning', 'evening'],
        suggestedDonation: {
            min: 2001,
            recommended: 5001,
        },
        category: 'special',
        frequency: 'on-request',
        tags: ['Charity', 'Community'],
        featured: false,
    },
    {
        id: '11',
        slug: 'vahana-seva',
        name: 'Vahana Seva',
        shortDescription: 'Deity procession on vahana (vehicle) with devotional singing',
        fullDescription: 'Lord Ganesha is taken in procession around the temple on His vahana (sacred vehicle - mouse) while devotees sing bhajans and offer prayers. A visually beautiful and spiritually uplifting experience.',
        benefits: [
            'Collective blessings',
            'Joyful devotion',
            'Community bonding',
            'Visual darshan',
        ],
        requirements: [
            'Performed on special occasions',
            'All devotees can participate',
            'Photography with permission',
        ],
        duration: '1 hour',
        timing: ['evening'],
        suggestedDonation: {
            min: 501,
            recommended: 1001,
        },
        category: 'weekly',
        frequency: 'weekly',
        tags: ['Processional', 'Festive'],
        featured: false,
    },
    {
        id: '12',
        slug: 'sankatahara-chaturthi',
        name: 'Sankatahara Chaturthi Vrat',
        shortDescription: 'Monthly vrat for removing difficulties and obstacles',
        fullDescription: 'Special vrat observed on the 4th day of Krishna Paksha (waning moon) specifically for removing difficulties. Includes fasting, special puja, and moon sighting.',
        benefits: [
            'Removal of specific obstacles',
            'Relief from difficulties',
            'Mental peace',
            'Moon blessings',
        ],
        requirements: [
            'Fasting till moonrise',
            'Breaking fast with prasadam',
            'Moon darshan essential',
        ],
        duration: '2 hours',
        timing: ['evening'],
        suggestedDonation: {
            min: 251,
            recommended: 501,
        },
        category: 'monthly',
        frequency: 'monthly',
        tags: ['Vrat', 'Evening'],
        featured: false,
    },
];
